import DS from 'ember-data';

var Progress = DS.Model.extend({
  name: DS.attr("string"),
  speakers: DS.attr("array"),
  links: DS.attr("array")
});

Progress.reopenClass({
  FIXTURES : [
    {
      id:0,
      name:"Acholi",
      links:["https://www.youtube.com/watch?v=_lTVSjRv10k"]
    },
    {
      id:1,
      name:"Afrikaans",
      links:["https://www.youtube.com/watch?v=CG0OnKUqziA"]
    },
    {
      id:2,
      name:"Albanian",
      links:["https://www.youtube.com/watch?v=T9JkzyrvbP4"]
    },
    {
      id:3,
      name:"Albanian, Gheg",
      links:["https://www.youtube.com/watch?v=gygesoisNhw"]
    },
    {
      id:4,
      name:"Arabic, North Levantine Spoken",
      links:["https://www.youtube.com/watch?v=72L2JsuGcH0"]
    },
    {
      id:5,
      name:"Arabic, South Levantine Spoken",
      links:["http://www.youtube.com/watch?v=nqOtvem2dxs"]
    },
    {
      id:6,
      name:"Aragonese",
      links:["http://www.youtube.com/watch?v=v2jD_SU9KZo"]
    },
    {
      id:7,
      name:"Argentine Sign Language",
      links:["https://www.youtube.com/watch?v=lhufdY1uT3k"]
    },
    {
      id:8,
      name:"Armenian",
      links:["http://www.youtube.com/watch?v=AUtRgfFUCl8"]
    },
    {
      id:9,
      name:"Aromanian",
      links:[" https://www.youtube.com/watch?v=dDQLdHkhPTE"]
    },
    {
      id:10,
      name:"Avar",
      links:["https://www.youtube.com/watch?v=FIFrZ0Fk9oY"]
    },
    {
      id:11,
      name:"Aymara",
    },
    {
      id:12,
      name:"Azerbaijani",
      links:["https://www.youtube.com/watch?v=fMTSDqjcvEk"]
    },
    {
      id:13,
      name:"Azerbaijani, North",
      links:["https://www.youtube.com/watch?v=kb3Xs56iCg8"]
    },
    {
      id:14,
      name:"Balkan Gagauz Turkish",
      links:["https://www.youtube.com/watch?v=CW8z9FeyOZ0"]
    },
    {
      id:15,
      name:"Basque",
      links:["http://www.youtube.com/watch?v=suK34prc56o"]
    },
    {
      id:16,
      name:"Batak Toba",
    },
    {
      id:17,
      name:"Bavarian",
    },
    {
      id:18,
      name:"Belarusan",
    },
    {
      id:19,
      name:"Bengali",
      links:["https://www.youtube.com/watch?v=Uq2x_P34bTQ"]
    },
    {
      id:20,
      name:"Bislama",
      links:[" https://www.youtube.com/watch?v=RHJOlCbQbbU"]
    },
    {
      id:21,
      name:"Bosnian",
      links:["https://www.youtube.com/watch?v=sQXzn-H0kjY"]
    },
    {
      id:22,
      name:"Bulgarian",
      links:["https://www.youtube.com/watch?v=57m0PfhE68c"]
    },
    {
      id:23,
      name:"Catalan",
      links:["http://www.youtube.com/watch?v=M6ZdYNFo6gM"]
    },
    {
      id:24,
      name:"Cebuano",
      links:["https://www.youtube.com/watch?v=nFLhxxsN7gQ"]
    },
    {
      id:25,
      name:"Chechen",
    },
    {
      id:26,
      name:"Cherokee",
      links:["http://www.youtube.com/watch?v=PUYoRT2EA5Q"]
    },
    {
      id:27,
      name:"Chonyi",
    },
    {
      id:28,
      name:"Chidigo",
    },
    {
      id:29,
      name:"Chiduruma",
    },
    {
      id:30,
      name:"Chinese, Mandarin",
      links:["https://www.youtube.com/watch?v=G5WqvFD-ELo"]
    },
    {
      id:31,
      name:"Chinese, Min Nan",
      links:["http://www.youtube.com/watch?v=--DnU743JLU"]
    },
    {
      id:32,
      name:"Chinese, Wu",
      links:["https://www.youtube.com/watch?v=8LWbdvQhn3E"]
    },
    {
      id:33,
      name:"Chinese, Yue",
      links:["http://www.youtube.com/watch?v=Ki4W4QVm2Hk"]
    },
    {
      id:34,
      name:"Chuwabu",
      links:["https://www.youtube.com/watch?v=PpNr0MgTAbY"]
    },
    {
      id:35,
      name:"Cimbrian",
    },
    {
      id:36,
      name:"Cornish",
      links:["https://www.youtube.com/watch?v=9UaAyI-uI30"]
    },
    {
      id:37,
      name:"Croatian",
    },
    {
      id:38,
      name:"Czech",
      links:["https://www.youtube.com/watch?v=8i4EEb5QMgU"]
    },
    {
      id:39,
      name:"Daakaka",
      links:["https://www.youtube.com/watch?v=_nZiBMOqcUU"]
    },
    {
      id:40,
      name:"Danish",
      links:["https://www.youtube.com/watch?v=-TEtqv0RTew"]
    },
    {
      id:41,
      name:"Dari",
      links:["http://www.youtube.com/watch?v=Yxrq9zhgla8"]
    },
    {
      id:42,
      name:"Dholuo",
      links:["https://www.youtube.com/watch?v=dxtFwV5Es7k"]
    },
    {
      id:43,
      name:"Dutch",
      links:["http://www.youtube.com/watch?v=Qv53zmmpM5Q"]
    },
    {
      id:44,
      name:"Efate, North",
      links:["https://www.youtube.com/watch?v=pqPtJM4ZRQE"]
    },
    {
      id:45,
      name:"English",
      links:["http://www.youtube.com/watch?v=nqOtvem2dxs"]
    },
    {
      id:46,
      name:"Esperanto",
      links:["https://www.youtube.com/watch?v=TotFWZLrQAY"]
    },
    {
      id:47,
      name:"Fijian",
      links:["https://www.youtube.com/watch?v=pFXjD9J-JE0"]
    },
    {
      id:48,
      name:"Finnish",
      links:["http://www.youtube.com/watch?v=FxrCNf8utsE"]
    },
    {
      id:49,
      name:"French",
      links:[" http://www.youtube.com/watch?v=VgzHAbJjteQ"]
    },
    {
      id:50,
      name:"Fulfulde, Central-Eastern Niger",
      links:["https://www.youtube.com/watch?v=1uIg0COZE5A"]
    },
    {
      id:51,
      name:"Gaelic, Scottish",
      links:["https://www.youtube.com/watch?v=buK4KwQ2QcE"]
    },
    {
      id:52,
      name:"Galician",
      links:["https://www.youtube.com/watch?v=p85oX1cewf4"]
    },
    {
      id:53,
      name:"Georgian",
      links:["https://www.youtube.com/watch?v=EqvGJERHbOY"]
    },
    {
      id:54,
      name:"German, Standard",
      links:["http://www.youtube.com/watch?v=9OkYYixgCes"]
    },
    {
      id:55,
      name:"German, Swiss",
      links:["https://www.youtube.com/watch?v=Flo8cPtcg6o"]
    },
    {
      id:56,
      name:"Gikuyu",
      links:["http://www.youtube.com/watch?v=SWn1t4o0QC0"]
    },
    {
      id:57,
      name:"Greek",
      links:["https://www.youtube.com/watch?v=bjjjwTvxcVI"]
    },
    {
      id:58,
      name:"Guaraní, Paraguayan",
    },
    {
      id:59,
      name:"Hausa",
    },
    {
      id:60,
      name:"Hebrew",
      links:["http://www.youtube.com/watch?v=vO87PpdQKV4"]
    },
    {
      id:61,
      name:"Hindi",
      links:["https://www.youtube.com/watch?v=hwQbxuwXGhc"]
    },
    {
      id:62,
      name:"Icelandic",
      links:["https://www.youtube.com/watch?v=NzKGubQLxTE"]
    },
    {
      id:63,
      name:"Indonesian",
      links:["https://www.youtube.com/watch?v=M5alRFKK43Y"]
    },
    {
      id:64,
      name:"Inuktitut, Greenlandic",
    },
    {
      id:65,
      name:"Irish",
      links:["https://www.youtube.com/watch?v=674za6Yr3Po"]
    },
    {
      id:66,
      name:"Italian",
      links:["http://www.youtube.com/watch?v=jjiXgRO8qDw"]
    },
    {
      id:67,
      name:"Jamaican Creole English",
      links:["https://www.youtube.com/watch?v=DmvDD9kJipE"]
    },
    {
      id:68,
      name:"Japanese",
      links:["http://www.youtube.com/watch?v=3up-hGFnYF0"]
    },
    {
      id:69,
      name:"Javanese",
    },
    {
      id:70,
      name:"Judeo-Tat",
    },
    {
      id:71,
      name:"Kannada",
      links:["https://www.youtube.com/watch?v=753D2NuKgKU"]
    },
    {
      id:72,
      name:"Kanuri",
    },
    {
      id:73,
      name:"Khmer, Central",
      links:["http://www.youtube.com/watch?v=xSaGl8fiiYk"]
    },
    {
      id:74,
      name:"Kigiryama",
    },
    {
      id:75,
      name:"Konkani",
      links:["https://www.youtube.com/watch?v=IahmVXN7xEQ"]
    },
    {
      id:76,
      name:"Korean",
      links:["https://www.youtube.com/watch?v=z_f7kpXW0tQ"]
    },
    {
      id:77,
      name:"K’iche’",
      links:["http://www.youtube.com/watch?v=7zQSfU5HkUc"]
    },
    {
      id:78,
      name:"Ladin",
    },
    {
      id:79,
      name:"Lakota",
    },
    {
      id:80,
      name:"Latvian, Standard",
      links:["https://www.youtube.com/watch?v=H3g87x0nL1M"]
    },
    {
      id:81,
      name:"Lau",
      links:["https://www.youtube.com/watch?v=Rm9fBd0k1LY"]
    },
    {
      id:82,
      name:"Laz",
      links:["https://www.youtube.com/watch?v=VXdN-FGePgc"]
    },
    {
      id:83,
      name:"Limburgish",
      links:["https://www.youtube.com/watch?v=cyhc6ddqdhc"]
    },
    {
      id:84,
      name:"Lombard",
      links:["http://www.youtube.com/watch?v=m2chaNIt3pk"]
    },
    {
      id:85,
      name:"Louisiana Creole French",
      links:["http://www.youtube.com/watch?v=Vg4cGwY-q2c"]
    },
    {
      id:86,
      name:"Luxembourgish",
      links:["http://www.youtube.com/watch?v=z1Jfor9KJdE"]
    },
    {
      id:87,
      name:"Macedonian",
    },
    {
      id:88,
      name:"Malagasy",
    },
    {
      id:89,
      name:"Malay, Ambonese",
      links:["https://www.youtube.com/watch?v=IvwbztWHe0I"]
    },
    {
      id:90,
      name:"Malayalam",
      links:["https://www.youtube.com/watch?v=KBUq9opT7Zg"]
    },
    {
      id:91,
      name:"Maori",
      links:["http://www.youtube.com/watch?v=OFHx0-4wU38"]
    },
    {
      id:92,
      name:"Mapudungun",
      links:["https://www.youtube.com/watch?v=9p-xnXddSy8"]
    },
    {
      id:93,
      name:"Marathi",
      links:["https://www.youtube.com/watch?v=hwQbxuwXGhc"]
    },
    {
      id:94,
      name:"Marwari",
      links:["https://www.youtube.com/watch?v=hwQbxuwXGhc"]
    },
    {
      id:95,
      name:"Mekeo",
      links:["https://www.youtube.com/watch?v=z3ou0vZj_80"]
    },
    {
      id:96,
      name:"Mingrelian",
      links:["https://www.youtube.com/watch?v=4XEKU1ZzQJQ"]
    },
    {
      id:97,
      name:"Nafusi",
      links:["https://www.youtube.com/watch?v=-7Ch2p6xPAM"]
    },
    {
      id:98,
      name:"Nahuatl, Central",
      links:["http://www.youtube.com/watch?v=w9MvPytHDvk"]
    },
    {
      id:99,
      name:"Nahuatl, Central Huasteca",
      links:["https://www.youtube.com/watch?v=8IvBOcstwCU&feature=youtu.be"]
    },
    {
      id:100,
      name:"Naskapi",
      links:["https://www.youtube.com/watch?v=9TCr5HMZp2w"]
    },
    {
      id:101,
      name:"Neverver",
      links:["https://www.youtube.com/watch?v=RHJOlCbQbbU"]
    },
    {
      id:102,
      name:"Norwegian",
      links:["http://www.youtube.com/watch?v=fk3Cq0mR6_4"]
    },
    {
      id:103,
      name:"Occitan",
      links:["http://www.youtube.com/watch?v=_IXEev5Z7ao"]
    },
    {
      id:104,
      name:"Penan, Western",
      links:["https://www.youtube.com/watch?v=Oz0hBgB5ixs"]
    },
    {
      id:105,
      name:"Polish",
      links:["https://www.youtube.com/watch?v=9pBaJojzNOI"]
    },
    {
      id:106,
      name:"Pontic",
    },
    {
      id:107,
      name:"Portuguese",
      links:["http://www.youtube.com/watch?v=tqftb3zad1o"]
    },
    {
      id:108,
      name:"Quechua",
      links:["https://www.youtube.com/watch?v=9p-xnXddSy8"]
    },
    {
      id:109,
      name:"Romagnol",
    },
    {
      id:110,
      name:"Romani, Balkan",
      links:["https://www.youtube.com/watch?v=zLTgmdLaQJ4"]
    },
    {
      id:111,
      name:"Russian",
      links:["http://www.youtube.com/watch?v=At6KGp45FdM"]
    },
    {
      id:112,
      name:"Sa",
      links:["https://www.youtube.com/watch?v=j6voxaLLoDw"]
    },
    {
      id:113,
      name:"Scots",
      links:["https://www.youtube.com/watch?v=le3cBRlWSE8"]
    },
    {
      id:114,
      name:"Sea Island Creole English",
      links:["http://www.youtube.com/watch?v=iCd5W4gwJsI"]
    },
    {
      id:115,
      name:"Segeju",
    },
    {
      id:116,
      name:"Sena",
      links:["https://www.youtube.com/watch?v=9D2ZymNG4rE&feature=youtu.be"]
    },
    {
      id:117,
      name:"Serbian",
      links:["http://www.youtube.com/watch?v=BIV7gCJRY0k"]
    },
    {
      id:118,
      name:"Shona",
      links:["http://www.youtube.com/watch?v=ZtXr7bckLyc"]
    },
    {
      id:119,
      name:"Slovene",
    },
    {
      id:120,
      name:"Somali",
      links:["https://www.youtube.com/watch?v=Ribtybmtb3k"]
    },
    {
      id:121,
      name:"Sorbian, Upper",
    },
    {
      id:122,
      name:"Spanish",
      links:["http://www.youtube.com/watch?v=OFHx0-4wU38"]
    },
    {
      id:123,
      name:"Svan",
    },
    {
      id:124,
      name:"Swahili",
      links:[" https://www.youtube.com/watch?v=Ribtybmtb3k"]
    },
    {
      id:125,
      name:"Swedish",
      links:["https://www.youtube.com/watch?v=o6FUP_2RmcI"]
    },
    {
      id:126,
      name:"Tamil",
      links:["https://www.youtube.com/watch?v=fMRTimDnx4A"]
    },
    {
      id:127,
      name:"Tat, Muslim",
    },
    {
      id:128,
      name:"Telugu",
      links:["https://www.youtube.com/watch?v=E-hVDqrQq6M"]
    },
    {
      id:129,
      name:"Thai",
      links:["http://www.youtube.com/watch?v=L2ST-UU6Ns"]
    },
    {
      id:130,
      name:"Thai, Northeastern",
      links:["https://www.youtube.com/watch?v=buuGVrfI2jo"]
    },
    {
      id:131,
      name:"Tharu, Kochila",
    },
    {
      id:132,
      name:"Totonac, Coyutla",
      links:["http://www.youtube.com/watch?v=cC50MO--CGQ"]
    },
    {
      id:133,
      name:"Tsakhur",
    },
    {
      id:134,
      name:"Tsakonian",
      links:["https://www.youtube.com/watch?v=bx44S_NctZg"]
    },
    {
      id:135,
      name:"Tsonga",
      links:["https://www.youtube.com/watch?v=8RyDKy_HUj0"]
    },
    {
      id:136,
      name:"Turkish",
      links:["https://www.youtube.com/watch?v=Kz6bU7RqIjc"]
    },
    {
      id:137,
      name:"Udi",
    },
    {
      id:138,
      name:"Urdu",
      links:[" http://www.youtube.com/watch?v=pru-95YczT4"]
    },
    {
      id:139,
      name:"Venetian",
    },
    {
      id:140,
      name:"Vietnamese",
    },
    {
      id:141,
      name:"Welsh",
      links:["https://www.youtube.com/watch?v=fvtbdq3WiyU"]
    },
    {
      id:142,
      name:"Yugoslavian Sign Language",
      links:["https://www.youtube.com/watch?v=SGTGWJf4dWw"]
    },
    {
      id:143,
      name:"Zazaki, Northern",
      links:["https://www.youtube.com/watch?v=fO0ZyO_Yk9I"]
    },
    {
      id:144,
      name:"Zulu",
      links:["http://www.youtube.com/watch?v=1tgBuR2dWh4"]
    }
  ]
});

export default Progress;

